#%RAML 1.0 NamedExample
meta: 
  messages: 
    - severity: INFO
      code: "200"
      description: OK
      link: 
        href: http://localhost
        title: All good!
  totalItems: 2
  pagingOffset: 1
  pagingLimit: 15

links: 
  self: 
    href: http://localhost/currentPage
    title: Current page
  first: 
    href: http://localhost/firstPage
    title: First Page
  prev: 
    href: http://localhost/previousPage
    title: Previous page
  next: 
    href: http://localhost/nextPage
    title: Next Page
  last: 
    href: http://localhost/lastPage
    title: Last Page
  
notifications:
- type: email
  recipient: brett@gmail.com
  subject: Hello
  priority: Info
  message: Welcome
- type: SMS
  recipient: 212345834
  subject: Hello
  priority: Info
  message: Welcome