#%RAML 1.0 NamedExample
- type: email
  recipient: brett@gmail.com
  subject: Hello
  priority: Info
  message: Welcome
- type: SMS
  recipient: 212345834
  subject: Hello
  priority: Info
  message: Welcome